// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHkuDgjBPoaPDga5mGRcM7EfoMyK1JV3I',
    appId: '1:157588721391:web:26bf4a0bc18b316ecdd51a',
    messagingSenderId: '157588721391',
    projectId: 'cryptoapp-804d8',
    authDomain: 'cryptoapp-804d8.firebaseapp.com',
    storageBucket: 'cryptoapp-804d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx6xY6uVxg14og_rwdmcfhuObkW3rNxgE',
    appId: '1:157588721391:android:f486834abd0ff17ecdd51a',
    messagingSenderId: '157588721391',
    projectId: 'cryptoapp-804d8',
    storageBucket: 'cryptoapp-804d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Gkyryn9tjgA8TPQYIw1-Bi0TTiM19lE',
    appId: '1:157588721391:ios:10e4aebb9a2e87a8cdd51a',
    messagingSenderId: '157588721391',
    projectId: 'cryptoapp-804d8',
    storageBucket: 'cryptoapp-804d8.appspot.com',
    iosBundleId: 'com.example.cryptoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Gkyryn9tjgA8TPQYIw1-Bi0TTiM19lE',
    appId: '1:157588721391:ios:5b301f08089785c6cdd51a',
    messagingSenderId: '157588721391',
    projectId: 'cryptoapp-804d8',
    storageBucket: 'cryptoapp-804d8.appspot.com',
    iosBundleId: 'com.example.cryptoapp.RunnerTests',
  );
}
